### ISSUE TITLE
Several Errors

### ISSUE THREAD

**Issue by coco0325** [dfsek-org/BetterEnd-Public#53] opened 2020-07-04 01:28 UTC
**Describe the bug**
Errors shown.
Log: https://pastebin.com/GtKuxgLS

**To Reproduce**
Go around the world.

**Expected behavior**
No errors.

**Versions**
[09:27:35 INFO]: This server is running Paper version git-Paper-43 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)
[09:27:35 INFO]: Checking version, please wait...
[09:27:36 INFO]: Previous version: git-Paper-33 (MC: 1.16.1)
[09:27:36 INFO]: You are 3 version(s) behind
[09:27:56 INFO]: [BetterEnd] This server is running BetterEnd v3.6.3

**Comment by dfsek** [comment] 2020-07-04 01:32
This was caused by an issue with the quantity of items being selected. Fix will be included in the next release.

**Comment by dfsek** [comment] 2020-07-04 01:33
As for the BlockState warnings, those may safely be ignored.

**Comment by dfsek** [comment] 2020-08-01 00:13
Fixed in 3.6.4

**Closed by dfsek** 2020-08-01 00:13 UTC
Labels: bug, pending release
